#pragma once

/** @file custom.h @brief All custom.* proprietary capabilities (generated). */

#include "custom/accessibility.h"
#include "custom/deodor_filter.h"
#include "custom/device_report_state_configuration.h"
#include "custom/disabled_capabilities.h"
#include "custom/disabled_components.h"
#include "custom/dishwasher_delay_start_time.h"
#include "custom/dishwasher_operating_percentage.h"
#include "custom/dishwasher_operating_progress.h"
#include "custom/dryer_dry_level.h"
#include "custom/dust_filter.h"
#include "custom/energy_type.h"
#include "custom/error.h"
#include "custom/fridge_mode.h"
#include "custom/job_beginning_status.h"
#include "custom/launchapp.h"
#include "custom/picturemode.h"
#include "custom/recording.h"
#include "custom/soundmode.h"
#include "custom/supported_options.h"
#include "custom/thermostat_setpoint_control.h"
#include "custom/tvsearch.h"
#include "custom/washer_auto_detergent.h"
#include "custom/washer_auto_softener.h"
#include "custom/washer_rinse_cycles.h"
#include "custom/washer_soil_level.h"
#include "custom/washer_spin_level.h"
#include "custom/washer_water_temperature.h"
#include "custom/water_filter.h"
