#pragma once

#include "oauth2_types.h"
#include "../types.h"
#include <map>
#include <string>

/**
 * @file oauth2_authenticator.h
 * @brief SmartThings OAuth 2.0 authorization-code flow: authorize URL + token exchange
 */

namespace smartthings4cpp {
namespace oauth2 {

    /**
     * @brief Drives the SmartThings OAuth 2.0 authorization-code flow
     *
     * Unlike a Personal Access Token, this class never performs any interactive
     * I/O itself: it has no opinion on how you present the authorize URL to the
     * user (browser, webview, printed to a terminal, ...) or how you captured
     * whatever the redirect handed back (a local listener, a manual paste, a
     * mobile deep link, ...). It only does the two things that are actually
     * protocol, not UX: build the authorize URL, and exchange a code (or a
     * refresh token) for an OAuth2Token via the SmartThings token endpoint.
     */
    class OAuth2Authenticator {
    public:
        /**
         * @brief Construct an authenticator for a self-registered OAuth-In App
         * @param config Client id/secret, scopes, and endpoint URLs (see OAuth2Config)
         */
        explicit OAuth2Authenticator(OAuth2Config config);

        /**
         * @brief Build the SmartThings authorize URL for a given redirect URI
         *
         * Generates a fresh CSRF @c state value, remembers it (together with
         * @p redirect_uri, which the token exchange must echo back), and embeds
         * it in the returned URL. Call this once per authorization attempt.
         * @param redirect_uri Must exactly match a redirect URI registered on
         *        the OAuth-In App (see @c smartthings @c apps:create)
         * @return The full authorize URL to present to the user
         */
        std::string buildAuthorizeUrl(const std::string& redirect_uri);

        /**
         * @brief Complete an authorization attempt and obtain a token
         *
         * Accepts either the full redirect URL (its query string is parsed for
         * @c code / @c state / @c error) or a bare authorization code. Rejects
         * the exchange if a @c state is present and doesn't match the value
         * generated by the preceding buildAuthorizeUrl() call, or if the
         * redirect carries an @c error (e.g. the user denied consent).
         * @param redirect_result Whatever was captured after the redirect
         * @return The access/refresh token pair on success
         */
        Result<OAuth2Token> completeAuthorization(const std::string& redirect_result);

        /**
         * @brief Exchange a refresh token for a new access/refresh token pair
         * @param refresh_token A refresh token from a previous OAuth2Token
         * @return The new access/refresh token pair on success
         * @note Using a refresh token resets its ~29-day idle expiry. Always
         *       persist whatever refresh_token comes back afterwards -
         *       SmartThings may rotate it, so the old one is not guaranteed to
         *       remain valid.
         */
        Result<OAuth2Token> refresh(const std::string& refresh_token);

    private:
        OAuth2Config _config;
        std::string _pending_state;
        std::string _pending_redirect_uri;

        Result<OAuth2Token> requestToken(const std::map<std::string, std::string>& form_params);
    };

} // namespace oauth2
} // namespace smartthings4cpp
